name: smartdriverid
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/zim_flag.png
    - assets/coat_of_arms.png
    - assets/licence_plastic.jpeg
    - assets/smartid-icon.png
    - assets/background-image.jpg
    - assets/background-image2.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/smartid-icon.png"
  min_sdk_android: 21
